=== g2p/xsf-documentation/extensions/xep.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT xep ( header, section1* ) >
<!ELEMENT header ( title, abstract, legal, number, status, type, sig, approver, dependencies, supersedes, supersededby, shortname, schemaloc*, registry?, expires?, author+, revision+ ) >
<!ELEMENT title (#PCDATA)* >
<!ELEMENT abstract (#PCDATA)* >
<!ELEMENT legal ( conformance, copyright, permissions, warranty ) >
<!ELEMENT conformance (#PCDATA | link)* >
<!ELEMENT copyright (#PCDATA | link)* >
<!ELEMENT permissions (#PCDATA | link)* >
<!ELEMENT warranty (#PCDATA | link)* >
<!ELEMENT number (#PCDATA)* >
<!ELEMENT status (#PCDATA)* >
<!ELEMENT type (#PCDATA)* >
<!ELEMENT sig (#PCDATA)* >
<!ELEMENT approver (#PCDATA)* >
<!ELEMENT dependencies ( spec* ) >
<!ELEMENT supersedes ( spec? ) >
<!ELEMENT supersededby ( spec? ) >
<!ELEMENT spec (#PCDATA)* >
<!ELEMENT shortname (#PCDATA)* >
<!ELEMENT schemaloc ( ns?, url ) >
<!ELEMENT ns (#PCDATA)* >
<!ELEMENT url (#PCDATA)* >
<!ELEMENT registry EMPTY>
<!ELEMENT expires (#PCDATA)* >
<!ELEMENT author ( firstname, surname, authornote?, org?, email?, jid?, uri? ) >
<!ELEMENT firstname (#PCDATA)* >
<!ELEMENT surname (#PCDATA)* >
<!ELEMENT authornote EMPTY>
<!ELEMENT org (#PCDATA)* >
<!ELEMENT email (#PCDATA)* >
<!ELEMENT jid (#PCDATA)* >
<!ELEMENT uri (#PCDATA)* >
<!ELEMENT revision ( version, date, initials, remark ) >
<!ELEMENT version (#PCDATA)* >
<!ELEMENT date (#PCDATA)* >
<!ELEMENT initials (#PCDATA)* >
<!ELEMENT remark ( p | ul )* >
<!ELEMENT section1 ( div | p | section2 | example | code | ul | ol | table )* >
<!ATTLIST section1
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section2 ( div | p | section3 | example | code | ul | ol | table )* >
<!ATTLIST section2
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section3 ( div | p | section4 | example | code | ul | ol | table )* >
<!ATTLIST section3
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section4 ( div | p | example | code | ul | ol | table )* >
<!ATTLIST section4
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT div ( div | p | example | code | ul | ol | table )* >
<!ATTLIST div 
          class CDATA ''
          style CDATA '' >
<!ELEMENT p (#PCDATA | img | link | note | tt | dfn | em | strong | cite | span)* >
<!ATTLIST p 
          class CDATA ''
          style CDATA '' >
<!ELEMENT ul (li+) >
<!ATTLIST ul 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT ol (li+) >
<!ATTLIST ol 
          class CDATA '' 
          start CDATA '' 
          style CDATA '' >
<!ELEMENT li (#PCDATA | p | link | note | tt | em | strong | span)* >
<!ATTLIST li 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA '' >
<!ELEMENT link (#PCDATA)* >
<!ATTLIST link url CDATA '' >
<!ELEMENT note (#PCDATA | link | tt | dfn | em | strong | cite | span)* >
<!ELEMENT example (#PCDATA)* >
<!ATTLIST example caption CDATA '' >
<!ELEMENT code (#PCDATA)* >
<!ATTLIST code caption CDATA '' >
<!ELEMENT table (tr)* >
<!ATTLIST table caption CDATA '' >
<!ELEMENT tr ( th | td )* >
<!ELEMENT th (#PCDATA)* >
<!ATTLIST th 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT td (#PCDATA)* >
<!ATTLIST td 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT tt (#PCDATA)* >
<!ELEMENT dfn (#PCDATA)* >
<!ELEMENT em (#PCDATA)* >
<!ELEMENT strong (#PCDATA)* >
<!ELEMENT cite (#PCDATA)* >
<!ELEMENT span (#PCDATA)* >
<!ATTLIST span 
          class CDATA ''
          style CDATA '' >

=== g2p/xsf-documentation/extensions/xep-0211.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>XMPP Basic Client 2008</title>
  <abstract>This document defines the XMPP Basic Client 2008 compliance level.</abstract>
  &LEGALNOTICE;
  <number>0211</number>
  <status>Proposed</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XMPP IM</spec>
    <spec>XEP-0030</spec>
    <spec>XEP-0106</spec>
    <spec>XEP-0115</spec>
    <spec>XEP-0138</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>N/A</shortname>
  &stpeter;
  <revision>
    <version>0.3</version>
    <date>2007-06-11</date>
    <initials>psa</initials>
    <remark><p>Changed XMPP Core and XMPP IM references to bis drafts; added implementation notes.</p></remark>
  </revision>
  <revision>
    <version>0.2</version>
    <date>2007-05-11</date>
    <initials>psa</initials>
    <remark><p>Added JID Escaping (XEP-0106) and Stream Compression (XEP-0138) as recommended.</p></remark>
  </revision>
  <revision>
    <version>0.1</version>
    <date>2007-04-20</date>
    <initials>psa</initials>
    <remark><p>Initial published version.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2007-03-30</date>
    <initials>psa</initials>
    <remark><p>First draft, split from XEP-0073.</p></remark>
  </revision>
</header>
<section1 topic='Introduction' anchor='intro'>
  <p>The &XSF; defines protocol suites for the purpose of compliance testing and software certification. This document specifies the XMPP Basic Client 2008 certification level.</p>
</section1>
<section1 topic='Definition' anchor='def'>
  <p>The XMPP Basic Client 2008 certification level is defined as follows:</p>
  <table caption='Required and Recommended Specifications'>
    <tr>
      <th>Specification</th>
      <th>Requirement Level</th>
    </tr>
    <tr>
      <td><strong>&rfc3920bis;</strong></td>
      <td>REQUIRED *</td>
    </tr>
    <tr>
      <td><strong>&rfc3921bis;</strong></td>
      <td>REQUIRED *</td>
    </tr>
    <tr>
      <td><strong>&xep0030;</strong></td>
      <td>REQUIRED</td>
    </tr>
    <tr>
      <td><strong>&xep0106;</strong></td>
      <td>RECOMMENDED</td>
    </tr>
    <tr>
      <td><strong>&xep0115;</strong></td>
      <td>REQUIRED</td>
    </tr>
    <tr>
      <td><strong>&xep0138;</strong></td>
      <td>RECOMMENDED</td>
    </tr>
  </table>
  <p>* Note: &xmppcore; and &xmppim; are currently being revised to incorporate errata and feedback based on implementation experience; because it is expected that the revision process will be complete well before this compliance level takes effect, developers are advised to implement the specifications as defined in draft-saintandre-rfc3920bis and draft-saintandre-rfc3921bis rather than RFC 3920 and RFC 3921.</p>
</section1>
<section1 topic='Implementation Notes' anchor='impl'>
  <p>Some of the protocol specifications referenced herein have their own dependencies; developers must refer to the relevant specifications for further information.</p>
</section1>
<section1 topic='Security Considerations' anchor='security'>
  <p>This document introduces no additional security considerations above and beyond those defined in the documents on which it depends.</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p> 
</section1>
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <p>This document requires no interaction with the &REGISTRAR;.</p> 
</section1>
</xep>

=== g2p/xsf-documentation/extensions/xep-0233.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Use of Domain-Based Service Names in XMPP SASL Negotiation</title>
  <abstract>This specification defines a method by which a connection manager associated with an XMPP server can inform a connecting client about its domain-based service name.</abstract>
  &LEGALNOTICE;
  <number>0233</number>
  <status>Experimental</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <approver>Council</approver>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>draft-ietf-kitten-gssapi-domain-based-names</spec>
    <spec>draft-ietf-kitten-krb5-gssapi-domain-based-names</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>NOT YET ASSIGNED</shortname>
  &linuxwolf;
  &stpeter;
  &hildjj;
  <revision>
    <version>0.1</version>
    <date>2008-01-30</date>
    <initials>psa</initials>
    <remark><p>Initial published version.</p></remark>
  </revision>
  <revision>
    <version>0.0.2</version>
    <date>2007-12-11</date>
    <initials>mm/psa</initials>
    <remark><p>Corrected syntax.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2007-12-05</date>
    <initials>mm/psa</initials>
    <remark><p>First draft.</p></remark>
  </revision>
</header>

<section1 topic='Introduction' anchor='intro'>
  <p>In certain kinds of XMPP deployments, multiple connection managers associated with the XMPP server may be used to handle requests from connecting clients. When such an architecture is used in environments that make use of Kerberos V and negotiation of Simple Authentication and Security Layer (SASL) over XMPP, the connection manager may need to give the client additional information about its principal so that the client can obtain a proper ticket for authentication.</p>
  <p>This scenario was not addressed in &rfc3920;. However, the problem can now be solved using the concept of domain-based service names as described in &kittenspn;. In particular, because XMPP servers typically use the Kerberos V5 ("GSSAPI") SASL mechanism as described in &rfc4752;, they can communicate domain-based names as Kerberos V service principal names as described in &kittenspnkrb5;.</p>
  <p>Therefore this document defines a method for communication of Kerberos V domain-based service names in the context of SASL negotiation by XMPP entities.</p>
</section1>

<section1 topic='Protocol' anchor='proto'>
  <p>When a connection manager associated with an XMPP server needs to communicate additional information about its service principal name to a connecting client, it can do so by including a child element of the &lt;mechanisms/&gt; element during SASL negotation, as specified in &rfc3920bis;. In the case of the Kerberos V SASL mechanism, the child element is a &lt;hostname/&gt; element qualified by the 'urn:xmpp:tmp:domain-based-name' namespace &NSNOTE;. The &lt;hostname/&gt; element MUST include a 'mechanism' attribute, where the value MUST be "GSSAPI". The XML character data of the &lt;hostname/&gt; element shall specify the fully-qualified name of the connection manager (known as the hostname). The client then generates a domain-based service name from the provided hostname, following the format specified in <cite>draft-ietf-kitten-krb5-gssapi-domain-based-names</cite> (i.e., "protocol/hostname/domainname@REALM"):</p>
  <ul>
    <li>The <strong>protocol</strong> string MUST be "xmpp"</li>
    <li>The <strong>hostname</strong> string MUST be the XML character data of the &lt;hostname/&gt; element</li>
    <li>The <strong>domainname</strong> string MUST be the canonical name of the service</li>
    <li>The <strong>REALM</strong> string SHOULD be determined according to the network policies in effect (usually the domain name, in an uppercase mapping)</li>
  </ul>
  <p>Consider the example of an XMPP service whose canonical name is "example.com". A user may in fact connect to the physical machine "cm7.us.example.com". The hostname would be communicated as follows.</p>
  <example caption="Communicating the hostname"><![CDATA[
<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
  <mechanism>GSSAPI</mechanism>
  <mechanism>DIGEST-MD5</mechanism>
  <required/>
  <hostname xmlns='urn:xmpp:tmp:domain-based-name'
            mechanism='GSSAPI'>cm7.us.example.com</hostname>
</mechanisms> 
  ]]></example>
  <p>The client would then attempt to obtain a ticket for the domain-based principal "xmpp/cm7.us.example.com/example.com@EXAMPLE.COM".</p>
</section1>

<section1 topic='Security Considerations' anchor='security'>
  <p>The communication of hostnames during SASL negotiation is not known to introduce new security vulnerabilities. Communication of hostnames SHOULD NOT occur until after the underlying channel has been secured using Transport Layer Security (TLS; &rfc4346;) as described for XMPP in <cite>RFC 3920</cite> and <cite>rfc3920bis</cite>. For additional security considerations, refer to <cite>draft-ietf-kitten-gssapi-domain-based-names</cite> and <cite>draft-ietf-kitten-krb5-gssapi-domain-based-names</cite>.</p>
</section1>

<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p> 
</section1>

<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <section2 topic='Protocol Namespaces' anchor='ns'>
    <p>Until this specification advances to a status of Draft, its associated namespace shall be "urn:xmpp:tmp:domain-based-name"; upon advancement of this specification, the &REGISTRAR; shall issue a permanent namespace in accordance with the process defined in Section 4 of &xep0053;.</p>
  </section2>
</section1>

<section1 topic='XML Schema' anchor='schema'>
  <code><![CDATA[
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    targetNamespace='urn:xmpp:tmp:domain-based-name'
    xmlns='urn:xmpp:tmp:domain-based-name'
    elementFormDefault='qualified'>

  <xs:element name='hostname' type='xs:string'/>

</xs:schema>
  ]]></code>
</section1>

<section1 topic='Acknowledgements' anchor='ack'>
  <p>Thanks to Alexey Melnikov for his comments.</p>
</section1>

</xep>

=== g2p/xsf-documentation/extensions/xep-0157.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Contact Addresses for XMPP Services</title>
  <abstract>This document defines a method for specifying contact addresses related to an XMPP service.</abstract>
  &LEGALNOTICE;
  <number>0157</number>
  <status>Experimental</status>
  <type>Standards Track</type>
  <jig>Standards JIG</jig>
  <approver>Council</approver>
  <dependencies>
    <spec>XMPP Core</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>N/A</shortname>
  &stpeter;
  <author>
    <firstname>Jacek</firstname>
    <surname>Konieczny</surname>
    <email>jajcus@jajcus.net</email>
    <jid>jajcus@jabber.bnet.pl</jid>
  </author>
  <revision>
    <version>0.3</version>
    <date>2006-07-31</date>
    <initials>psa</initials>
    <remark><p>Recommended support for RFC2142-style mailbox in addition to XMPP address.</p></remark>
  </revision>
  <revision>
    <version>0.2</version>
    <date>2006-07-18</date>
    <initials>psa</initials>
    <remark><p>Removed extended addressing recommendations pending further review.</p></remark>
  </revision>
  <revision>
    <version>0.1</version>
    <date>2005-09-08</date>
    <initials>psa</initials>
    <remark><p>Initial version.</p></remark>
  </revision>
  <revision>
    <version>0.0.2</version>
    <date>2005-09-06</date>
    <initials>psa</initials>
    <remark><p>Added security considerations and XMPP Registrar considerations.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2005-08-27</date>
    <initials>psa/jk</initials>
    <remark><p>First draft.</p></remark>
  </revision>
</header>
<section1 topic='Introduction' anchor='intro'>
  &BISNOTE;
  <p>&rfc2142; specifies conventional electronic mailbox names for common services, roles, and functions related to SMTP, NNTP, and HTTP (such as postmaster@domain.tld, usenet@domain.tld, and webmaster@domain.tld). However, no such conventional email address or Jabber ID (JID) has been specified for XMPP services. This document remedies that oversight.</p>
</section1>
<section1 topic='XMPP Address' anchor='xmpp'>
  <p>Many existing Jabber/XMPP server implementations use the bare domain of the server as an alias for the server administrators, such that a &MESSAGE; stanza addressed to that domain name (e.g., "jabber.org") is delivered to the JIDs of the server administrators (this does not apply to &IQ; or &PRESENCE; stanzas). It is RECOMMENDED that all server implementations support this functionality, and the authors will work toward standardization of this functionality in the forthcoming revisions to &rfc3920;.</p>
</section1>
<section1 topic='Email Address' anchor='email'>
  <p>Consistent with <cite>RFC 2142</cite>, a domain that offers a Jabber/XMPP service SHOULD provide an Internet mailbox of "XMPP" for inquiries related to that service, which MAY be advertised through a URI of &lt;mailto:xmpp@domain.tld&gt;.</p>
</section1>
<!--
<section1 topic='Extended Server Information' anchor='disco'>
  <p>The administrators of a Jabber/XMPP service may desire to advertise more detailed contact information related to that service. This contact information may include email addresses, web URLs, and JIDs for specific roles and functions such as abuse reports, customer feedback, sales inquiries, technical support, and security concerns. For this purpose, domains MUST support the electronic mailboxes required by <cite>RFC 2142</cite>. However, additional contact mechanisms may be desirable, and it would be helpful if those who want to initiate contact could discover the contact information using standard XMPP extensions, specifically &xep0030;. To make such discovery possible, we specify a &xep0128; mechanism that a server MAY return in response to service discovery information ("disco#info") requests sent to the bare domain of the server. This information SHOULD be scoped using a FORM_TYPE of "http://jabber.org/network/serverinfo" (as already specified in <cite>XEP-0128</cite>) and data form fields registered for this purpose as defined in the <link url='#registrar'>XMPP Registrar Considerations</link> section of this document.</p>
  <p>To illustrate this usage, consider the following example of a disco#info request sent to the mythical shakespeare.lit XMPP server:</p>
  <example caption='Entity queries server for information'><![CDATA[
<iq from='juliet@capulet.com/chamber'
    to='shakespeare.lit'
    id='disco1'
    type='get'>
  <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>
    ]]></example>
    <example caption='Server communicates information'><![CDATA[
<iq from='shakespeare.lit'
    to='juliet@capulet.com/chamber'
    id='disco1'
    type='result'>
  <query xmlns='http://jabber.org/protocol/disco#info'>
    <identity category='server' type='im'/>
    <feature var='http://jabber.org/protocol/disco'/>
    <x xmlns='jabber:x:data' type='result'>
      <field var='FORM_TYPE' type='hidden'>
        <value>http://jabber.org/network/serverinfo</value>
      </field>
      <field var='abuse-addresses'>
        <value>mailto:abuse@shakespeare.lit</value>
        <value>xmpp:shakespeare.lit/abuse</value>
      </field>
      <field var='feedback-addresses'>
        <value>http://shakespeare.lit/feedback.php</value>
        <value>mailto:feedback@shakespeare.lit</value>
        <value>xmpp:shakespeare.lit/feedback</value>
      </field>
      <field var='sales-addresses'>
        <value>xmpp:bard@shakespeare.lit</value>
      </field>
      <field var='security-addresses'>
        <value>xmpp:shakespeare.lit/security</value>
      </field>
      <field var='support-addresses'>
        <value>http://shakespeare.lit/support.php</value>
        <value>xmpp:shakespeare.lit/support</value>
      </field>
    </x>
  </query>
</iq>
    ]]></example>
</section1>
-->
<section1 topic='Security Considerations' anchor='security'>
  <p>Advertising contact addresses may open those addresses to unwanted communication. Server administrators should balance the need for openness with the desire for control over communication with customers and peers. That said, certain contact addresses (e.g., abuse addresses and security addresses) may enable server administrators to more quickly learn of abusive usage and potential security holes, and advertisement of those addresses is strongly encouraged.</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p>
</section1>
<!--
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <p>The &REGISTRAR; shall include the following information in its registries.</p>
  <section2 topic='Field Standardization' anchor='registrar-formtype'>
    <p>&xep0068; defines a process for standardizing the fields used within Data Forms qualified by a particular namespace, and <cite>XEP-0128</cite> describes how to use field standardization in the context of service discovery. This section registers fields for server information scoped by the "http://jabber.org/network/serverinfo" FORM_TYPE.</p>
    <code caption='Registry Submission'><![CDATA[
<form_type>
  <name>http://jabber.org/network/serverinfo</name>
  <doc>XEP-0157</doc>
  <desc>
    Forms enabling the communication of contact addresses
    and other server information.
  </desc>
  <field
      var='abuse-addresses'
      type='list-multi'
      label='One or more addresses for communication related to abusive traffic'/>
  <field
      var='feedback-addresses'
      type='list-multi'
      label='One or more addresses for customer feedback'/>
  <field
      var='sales-addresses'
      type='list-multi'
      label='One or more addresses for communication related to sales and marketing'/>
  <field
      var='security-addresses'
      type='list-multi'
      label='One or more addresses for communication related to security concerns'/>
  <field
      var='support-addresses'
      type='list-multi'
      label='One or more addresses for customer support'/>
</form_type>
    ]]></code>
  </section2>
</section1>
-->
</xep>

=== g2p/xsf-documentation/extensions/xep-0256.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Last Activity in Presence</title>
  <abstract>This specification defines a way to use the Last Activity extension in XMPP presence notifications.</abstract>
  &LEGALNOTICE;
  <number>0256</number>
  <status>Experimental</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XMPP IM</spec>
    <spec>XEP-0012</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>N/A</shortname>
  &stpeter;
  <revision>
    <version>0.1</version>
    <date>2008-11-26</date>
    <initials>psa</initials>
    <remark><p>Initial published version; removed note about handling the absence of a last activity notation; added security considerations.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2008-11-20</date>
    <initials>psa</initials>
    <remark><p>Rough draft based on list discussion.</p></remark>
  </revision>
</header>
<section1 topic='Use Case' anchor='usecase'>
  <p>&xep0012; defines a method for determining the last time that an XMPP entity was active. This document specifies that an online client MAY include last activity information when sending presence updates. The prototypical use case is including the idle time when automatically setting the user's &SHOW; value to "away" or "xa" (extended away). For example, consider a user who has configured her client to automatically change her presence to "away" after 10 minutes of inactivity. The client could include an iq:last flag to specify how long the user has been idle.</p>
  <example caption='Last Indication in Auto-Away'><![CDATA[
<presence from='juliet@capulet.com/balcony'>
  <show>away</show>
  <query xmlns='jabber:iq:last' seconds='600'/>
</presence>
  ]]></example>
  <p>If one of the user's contacts receives that presence notification with delayed delivery (see &xep0203;) on login in response to a presence probe as described in &xmppim;, the contact will then know how long the user has been idle (i.e., the number of seconds since the delayed delivery timestamp, plus the iq:last seconds). Thus the contact does not need to send an iq:last query.</p>
  <example caption='Last Indication in Auto-Away With Delayed Delivery'><![CDATA[
<presence from='juliet@capulet.com/balcony' to='romeo@montague.net'>
  <show>away</show>
  <query xmlns='jabber:iq:last' seconds='600'/>
  <delay xmlns='urn:xmpp:delay'
     from='capulet.com'
     stamp='2002-09-10T23:41:07Z'/>
</presence>
  ]]></example>
</section1>
<section1 topic='Security Considerations' anchor='security'>
  <p>Including a last activity notation in presence notifications can enable those who receive such notifications to determine exactly when a user has stopped interacting with his or her XMPP client, but this information is in essence already available if the user publishes timely presence updates. Therefore, this specification introduces no new vulnerabilities.</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p>
</section1>
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <p>This document requires no interaction with the &REGISTRAR;.</p>
</section1>
</xep>

=== g2p/xsf-documentation/extensions/xep-0002.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Jabber Interest Groups (JIGs)</title>
  <abstract>A definition of Jabber Interest Groups, including their structure and role within the Jabber Software Foundation.</abstract>
  &LEGALNOTICE;
  <number>0002</number>
  <status>Active</status>
  <type>Procedural</type>
  <jig>None</jig>
  <approver>Board</approver>
  <dependencies/>
  <supersedes/>
  <supersededby/>
  &stpeter;
  <revision>
    <version>1.1</version>
    <date>2002-01-11</date>
    <initials>psa</initials>
    <remark>Clarified some details and added information about cut-offs for inactivity.</remark>
  </revision>
  <revision>
    <version>1.0</version>
    <date>2001-06-28</date>
    <initials>psa</initials>
    <remark>First release, modified from Rahul Dave's modification of my original post.</remark>
  </revision>
</header>
<section1 topic='Short Definition'>
  <p>A Jabber Interest Group (JIG) is a working group approved by the XMPP Council to address specific areas of growth or concern within the Jabber/XMPP developer community, usually by means of developing and publishing XMPP Extension Protocols (XEPs).</p>
</section1>
<section1 topic='Explanation'>
  <p>The main function of most JIGs is to produce acceptable XMPP extensions (delivered in the form of XMPP Extension Protocols or XEPs <note>For information about XMPP Extension Protocols, see <link url="http://www.xmpp.org/extensions/xep-0001.html">http://www.xmpp.org/extensions/xep-0001.html</link>.</note>) within a reasonably limited period of time. However, at the discretion of the XMPP Council, a handful of standing JIGs may be approved (e.g., to address security or standards compliance).</p>
  <p>Anyone (not limited to members of the Jabber Software Foundation) may propose the formation of a JIG by completing a XMPP Extension Protocol outlining the need for the JIG and its proposed focus. However, JIG leaders must be members of the Jabber Software Foundation. The number of leaders for a JIG is flexible, and shall be determined by each JIG, in consultation with the XMPP Council if necessary. The concept of "membership" with regard to JIGs is loose, and is essentially co-extensive with membership in the appropriate mailing list (each JIG has its own mailing list, which is archived for public review). JIG members do not need to be members of the Jabber Software Foundation, and any member of the general public may subscribe to JIG mailing lists.</p>
  <p>It is expected that all JIGs (other than certain standing JIGs) will remain active for as long as necessary in order to produce one or more standards-track JEPs for review by the XMPP Council in the JIG's area of focus. However, if a JIG does not show signs of activity for an extended period of time (usually six months of inactivity on the JIG's mailing list), the JIG may be disbanded at the discretion of the XMPP Council with appropriate warning to the JIG members (usually in the form of an email sent to the JIG's mailing list).</p>
</section1>
</xep>
