=== g2p/xsf-documentation/extensions/xep.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT xep ( header, section1* ) >
<!ELEMENT header ( title, abstract, legal, number, status, type, sig, approver, dependencies, supersedes, supersededby, shortname, schemaloc*, registry?, expires?, author+, revision+ ) >
<!ELEMENT title (#PCDATA)* >
<!ELEMENT abstract (#PCDATA)* >
<!ELEMENT legal ( conformance, copyright, permissions, warranty ) >
<!ELEMENT conformance (#PCDATA | link)* >
<!ELEMENT copyright (#PCDATA | link)* >
<!ELEMENT permissions (#PCDATA | link)* >
<!ELEMENT warranty (#PCDATA | link)* >
<!ELEMENT number (#PCDATA)* >
<!ELEMENT status (#PCDATA)* >
<!ELEMENT type (#PCDATA)* >
<!ELEMENT sig (#PCDATA)* >
<!ELEMENT approver (#PCDATA)* >
<!ELEMENT dependencies ( spec* ) >
<!ELEMENT supersedes ( spec? ) >
<!ELEMENT supersededby ( spec? ) >
<!ELEMENT spec (#PCDATA)* >
<!ELEMENT shortname (#PCDATA)* >
<!ELEMENT schemaloc ( ns?, url ) >
<!ELEMENT ns (#PCDATA)* >
<!ELEMENT url (#PCDATA)* >
<!ELEMENT registry EMPTY>
<!ELEMENT expires (#PCDATA)* >
<!ELEMENT author ( firstname, surname, authornote?, org?, email?, jid?, uri? ) >
<!ELEMENT firstname (#PCDATA)* >
<!ELEMENT surname (#PCDATA)* >
<!ELEMENT authornote EMPTY>
<!ELEMENT org (#PCDATA)* >
<!ELEMENT email (#PCDATA)* >
<!ELEMENT jid (#PCDATA)* >
<!ELEMENT uri (#PCDATA)* >
<!ELEMENT revision ( version, date, initials, remark ) >
<!ELEMENT version (#PCDATA)* >
<!ELEMENT date (#PCDATA)* >
<!ELEMENT initials (#PCDATA)* >
<!ELEMENT remark ( p | ul )* >
<!ELEMENT section1 ( div | p | section2 | example | code | ul | ol | table )* >
<!ATTLIST section1
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section2 ( div | p | section3 | example | code | ul | ol | table )* >
<!ATTLIST section2
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section3 ( div | p | section4 | example | code | ul | ol | table )* >
<!ATTLIST section3
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section4 ( div | p | example | code | ul | ol | table )* >
<!ATTLIST section4
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT div ( div | p | example | code | ul | ol | table )* >
<!ATTLIST div 
          class CDATA ''
          style CDATA '' >
<!ELEMENT p (#PCDATA | img | link | note | tt | dfn | em | strong | cite | span)* >
<!ATTLIST p 
          class CDATA ''
          style CDATA '' >
<!ELEMENT ul (li+) >
<!ATTLIST ul 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT ol (li+) >
<!ATTLIST ol 
          class CDATA '' 
          start CDATA '' 
          style CDATA '' >
<!ELEMENT li (#PCDATA | p | link | note | tt | em | strong | span)* >
<!ATTLIST li 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA '' >
<!ELEMENT link (#PCDATA)* >
<!ATTLIST link url CDATA '' >
<!ELEMENT note (#PCDATA | link | tt | dfn | em | strong | cite | span)* >
<!ELEMENT example (#PCDATA)* >
<!ATTLIST example caption CDATA '' >
<!ELEMENT code (#PCDATA)* >
<!ATTLIST code caption CDATA '' >
<!ELEMENT table (tr)* >
<!ATTLIST table caption CDATA '' >
<!ELEMENT tr ( th | td )* >
<!ELEMENT th (#PCDATA)* >
<!ATTLIST th 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT td (#PCDATA)* >
<!ATTLIST td 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT tt (#PCDATA)* >
<!ELEMENT dfn (#PCDATA)* >
<!ELEMENT em (#PCDATA)* >
<!ELEMENT strong (#PCDATA)* >
<!ELEMENT cite (#PCDATA)* >
<!ELEMENT span (#PCDATA)* >
<!ATTLIST span 
          class CDATA ''
          style CDATA '' >

=== g2p/xsf-documentation/extensions/xep-0186.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Invisible Command</title>
  <abstract>This document specifies an XMPP-compatible protocol for user invisibility.</abstract>
  &LEGALNOTICE;
  <number>0186</number>
  <status>Experimental</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XMPP IM</spec>
    <spec>XEP-0030</spec>
  </dependencies>
  <supersedes>None</supersedes>
  <supersededby>None</supersededby>
  <shortname>NOT YET ASSIGNED</shortname>
  &stpeter;
  <revision>
    <version>0.5</version>
    <date>2007-01-30</date>
    <initials>psa</initials>
    <remark><p>Modified XML namespace name to conform to XEP-0053 processes.</p></remark>
  </revision>
  <revision>
    <version>0.4</version>
    <date>2006-08-09</date>
    <initials>psa</initials>
    <remark><p>Added XMPP Registrar considerations and XML schema.</p></remark>
  </revision>
  <revision>
    <version>0.3</version>
    <date>2006-08-02</date>
    <initials>psa</initials>
    <remark><p>Added inbound presence rule to server handling section.</p></remark>
  </revision>
  <revision>
    <version>0.2</version>
    <date>2006-07-07</date>
    <initials>psa</initials>
    <remark><p>Clarified that invisibility mode does not carry across sessions.</p></remark>
  </revision>
  <revision>
    <version>0.1</version>
    <date>2006-05-30</date>
    <initials>psa</initials>
    <remark><p>Initial version.</p></remark>
  </revision>
  <revision>
    <version>0.0.2</version>
    <date>2006-05-15</date>
    <initials>psa</initials>
    <remark><p>Recommended delivery of messages sent to bare JID.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2006-05-11</date>
    <initials>psa</initials>
    <remark><p>First draft.</p></remark>
  </revision>
</header>
<section1 topic='Introduction' anchor='intro'>
  <p>Some instant messaging implementations of the Jabber/XMPP protocols have long supported the ability for IM users to be online but appear invisible. The existing protocols for doing so are:</p>
  <ul>
    <li><p>&xep0018; -- this protocol is not compatible with &xmppcore; and &xmppim;, and the speciifcation does not provide reliable documentation of the protocol in use since many server implementations support presence of type "invisible" but not presence of type "visible".</p></li>
    <li><p>&xep0126; -- this protocol is in many ways a mis-use of privacy lists for the temporary purpose of appearing invisible rather than the intended purpose of permanently blocking communications.</p></li>
  </ul>
  <p>In order to provide a standards-compliant protocol that can be used in the long term, this document defines an IQ-based protocol that enables an IM user to "go invisible" and "go visible" at will within the context of a given session.</p>
</section1>
<section1 topic='Requirements' anchor='req'>
  <p>The requirements for invisible mode are straightforward:</p>
  <ol start='1'>
    <li>A user should be able to become visible or invisible at any time within an XMPP session.</li>
    <li>Invisible mode is active only for the current session; if the user ends that session and starts another session, the invisibility mode set for the previous session does not carry over to the new session.</li>
    <li>When in invisible mode, a user should be able to send directed presence to particular contacts.</li>
  </ol>
</section1>
<section1 topic='Use Cases' anchor='usecases'>
  <section2 topic='Discovering Support' anchor='disco'>
    <p>In order for a client to discover whether its server supports the protocol defined herein, it MUST send a &xep0030; information request to the server:</p>
    <example caption='Service discovery request'><![CDATA[
<iq from='bilbo@tolkien.lit/shire' to='tolkien.lit' type='get' id='disco1'>
  <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>
    ]]></example>
    <p>If the server supports the protocol defined herein, it MUST return a feature of "http://www.xmpp.org/extensions/xep-0186.html#ns":</p>
    <example caption='Service discovery response'><![CDATA[
<iq from='bilbo@tolkien.lit/shire' to='tolkien.lit' type='get' id='disco1'>
  <query xmlns='http://jabber.org/protocol/disco#info'>
    ...
    <feature var='http://www.xmpp.org/extensions/xep-0186.html#ns'/>
    ...
  </query>
</iq>
    ]]></example>
    <p>A client SHOULD complete this service discovery process before sending initial presence to its server.</p>
  </section2>
  <section2 topic='User Becomes Invisible' anchor='invisible'>
    <p>In order for a client to go invisible, it shall send an IQ-set with no 'to' address (thus handled by the user's server) containing an &lt;invisible/&gt; element qualified by the 'http://www.xmpp.org/extensions/xep-0186.html#ns' namespace:</p>
    <example caption='Invisible command'><![CDATA[
<iq type='set' id='inv1'>
  <invisible xmlns='http://www.xmpp.org/extensions/xep-0186.html#ns'/>
</iq>
    ]]></example>
    <p>If the server can successfully process the invisibility command, it MUST return an IQ-result:</p>
    <example caption='Invisible command is successful'><![CDATA[
<iq type='result' id='inv1'/>
    ]]></example>
    <p>(Standard XMPP stanza errors apply; see <cite>RFC 3920</cite> and &xep0086;.)</p>
    <p>If the client enters invisible mode after having previously sent undirected presence with no 'type' attribute (e.g., after sending initial presence), the server MUST send &UNAVAILABLE; presence from the client's resource to all contacts who would receive unavailable presence if the client sent &UNAVAILABLE;.</p>
    <p>While the client is in invisible mode, the server:</p>
    <ol start='1'>
      <li><p>MUST NOT broadcast presence notifications as a result of receiving any subsequent undirected presence notifications from the client.</p></li>
      <li><p>MUST deliver directed presence stanzas generated by the client.</p></li>
      <li><p>MUST deliver inbound &PRESENCE; stanzas.</p></li>
      <li><p>SHOULD deliver inbound &MESSAGE; stanzas whose 'to' address is the bare JID (&BAREJID;) of the user (subject to standard XMPP stanza handling rules).</p></li>
      <li><p>MUST deliver inbound &MESSAGE; and &IQ; stanzas whose 'to' address is the full JID (&FULLJID;) corresponding to the resource of the client.</p></li>
      <li><p>MUST deliver outbound &MESSAGE; and &IQ; stanzas generated by the client (for an important note regarding presence leaks, see the <link url='#security'>Security Considerations</link> section of this document).</p></li>
    </ol>
    <p>If after sending directed presence the client then sends &UNAVAILABLE;, the server MUST deliver that unavailable presence only to the entities to which the client sent directed presence after going invisible.</p>
  </section2>
  <section2 topic='User Becomes Visible' anchor='visible'>
    <p>In order for a client to become visible again, it shall send an IQ-set with no 'to' address (thus handled by the user's server) containing a &lt;visible/&gt; element qualified by the 'http://www.xmpp.org/extensions/xep-0186.html#ns' namespace:</p>
    <example caption='Visible command'><![CDATA[
<iq type='set' id='vis1'>
  <visible xmlns='http://www.xmpp.org/extensions/xep-0186.html#ns'/>
</iq>
    ]]></example>
    <p>If the server can successfully process the visibility command, it MUST return an IQ-result:</p>
    <example caption='Visible command is successful'><![CDATA[
<iq type='result' id='vis1'/>
    ]]></example>
    <p>When the client becomes visible, the server MUST treat that state as equivalent to an active session before receiving initial presence from the client. It is the responsibility of the client to send an undirected presence notification to the server, which the server MUST broadcast to all entities who would normally receive presence broadcasts from the client (as well as any other entities to which the client sent directed presence while invisible).</p>
  </section2>
</section1>
<section1 topic='Security Considerations' anchor='security'>
  <p>It is possible to leak presence while in invisible mode (for example, by sending a message, IQ, or presence stanza to a contact). A client SHOULD warn a user before allowing the client to generate any outbound traffic and MUST NOT respond to IQ requests received from entities with which it has not initiated communications while in invisible mode (e.g., by sending messages, IQs, or directed presence).</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>No interaction with &IANA; is required as a result of this document.</p>
</section1>
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <section2 topic='Protocol Namespaces' anchor='ns'>
    <p>Until this specification advances to a status of Draft, its associated namespace shall be "http://www.xmpp.org/extensions/xep-00186.html#ns"; upon advancement of this specification, the &REGISTRAR; shall issue a permanent namespace in accordance with the process defined in Section 4 of &xep0053;.</p>
  </section2>
</section1>
<section1 topic='XML Schema' anchor='schema'>
  <code><![CDATA[
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    targetNamespace='http://www.xmpp.org/extensions/xep-0186.html#ns'
    xmlns='http://www.xmpp.org/extensions/xep-0186.html#ns'
    elementFormDefault='qualified'>

  <xs:element name='invisible' type='empty'/>

  <xs:element name='visible' type='empty'/>

  <xs:simpleType name='empty'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value=''/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
  ]]></code>
</section1>
</xep>

=== g2p/xsf-documentation/extensions/xep-0249.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Direct MUC Invitations</title>
  <abstract>This specification defines a method for inviting a contact to a multi-user chat room directly, instead of sending the invitation through the chat room.</abstract>
  &LEGALNOTICE;
  <number>0249</number>
  <status>Experimental</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <approver>Council</approver>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XEP-0045</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>NOT_YET_ASSIGNED</shortname>
  &stpeter;
  <revision>
    <version>0.1</version>
    <date>2008-09-03</date>
    <initials>psa</initials>
    <remark><p>Initial published version.</p></remark>
  </revision>
  <revision>
    <version>0.0.5</version>
    <date>2008-09-02</date>
    <initials>psa</initials>
    <remark><p>Modified to use old jabber:x:conference namespace.</p></remark>
  </revision>
  <revision>
    <version>0.0.4</version>
    <date>2008-08-18</date>
    <initials>psa</initials>
    <remark><p>Added note about handling multiple invitations.</p></remark>
  </revision>
  <revision>
    <version>0.0.3</version>
    <date>2008-08-16</date>
    <initials>psa</initials>
    <remark><p>Added implementation note about members-only rooms.</p></remark>
  </revision>
  <revision>
    <version>0.0.2</version>
    <date>2008-08-14</date>
    <initials>psa</initials>
    <remark><p>Changed venue element to conference element.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2008-08-12</date>
    <initials>psa</initials>
    <remark><p>First draft.</p></remark>
  </revision>
</header>

<section1 topic='Introduction' anchor='intro'>
  <p>&xep0045; defines a protocol for groupchat over XMPP. That specification includes a method for inviting a contact to a room, where the invitation is mediated by the room itself: the user sends the invitation to the room, which in turn sends it to the contact. Unfortunately, a mediated invitation might not be delivered to the contact, for example if the contact blocks communication with entities not in its roster as specified in &xep0016;. As privacy lists have become more common, MUC invitations have been increasingly blocked at the server side, resulting in an undesirable user experience. Therefore, this specification defines a method for sending an invitation directly from the user to the contact, which re-uses the original 'jabber:x:conference' namespace in use before XEP-0045 was written.</p> 
</section1>

<section1 topic='How It Works' anchor='howitworks'>
  <p>A user invites a contact to a room by sending a &MESSAGE; stanza containing only an &lt;invitation/&gt; element qualified by the 'jabber:x:conference' namespace &NSNOTE;.</p>
  <example caption="A direct invitation"><![CDATA[
<message
    from='crone1@shakespeare.lit/desktop'
    to='hecate@shakespeare.lit'>
  <x xmlns='jabber:x:conference'
     jid='darkcave@macbeth.shakespeare.lit'/>
</message>
  ]]></example>
  <p>The 'jid' attribute is REQUIRED.</p>
  <p>Upon receiving a direct invitation, the contact's client SHOULD present the invitation to the contact so that the contact can accept it or decline it. If the contact accepts the invitation, the contact's client shall join the room as described in <cite>XEP-0045</cite>. If the contact declines the invitation, it shall silently discard the invitation.</p>
</section1>

<section1 topic='Determining Support' anchor='support'>
  <p>If an entity supports the protocol specified herein, it MUST advertise that fact by returning a feature of "jabber:x:conference" in response to &xep0030; information requests &NSNOTE;.</p>
  <example caption="Service discovery information request"><![CDATA[
<iq from='crone1@shakespeare.lit/desktop'
    id='disco1'
    to='hecate@shakespeare.lit/broom'
    type='get'>
  <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>
  ]]></example>
  <example caption="Service discovery information response"><![CDATA[
<iq from='hecate@shakespeare.lit/broom'
    id='disco1'
    to='crone1@shakespeare.lit/desktop'
    type='result'>
  <query xmlns='http://jabber.org/protocol/disco#info'>
    ...
    <feature var='jabber:x:conference'/>
    ...
  </query>
</iq>
  ]]></example>
  <p>In order for an application to determine whether an entity supports this protocol, where possible it SHOULD use the dynamic, presence-based profile of service discovery defined in &xep0115;. However, if an application has not received entity capabilities information from an entity, it SHOULD use explicit service discovery instead.</p>
</section1>

<section1 topic='Implementation Notes' anchor='impl'>
  <p>Before inviting a contact to a members-only room, a user SHOULD check to see if the contact is already a member and, if not, add the contact to the member list (or ask a room administrator to do so).</p>
  <p>If a client receives multiple invitations to the same room (e.g., a mediated invitation as defined in <cite>XEP-0045</cite> and a direct invitation as defined here), the client SHOULD present only one of the invitations to a human user. If a client receives an invitation to a room in which the user is already an occupant, the client SHOULD silently discard the invitation.</p>
</section1>

<section1 topic='Security Considerations' anchor='security'>
  <p>To follow.</p>
</section1>

<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p> 
</section1>

<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <section2 topic='Protocol Namespaces' anchor='ns'>
    <p>Upon advancement of this specification to a status of Draft, the &REGISTRAR; shall add 'jabber:x:conference' to its registry of protocol namespaces.</p>
  </section2>
</section1>

<section1 topic='XML Schema' anchor='schema'>
  <code><![CDATA[
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    targetNamespace='jabber:x:conference'
    xmlns='jabber:x:conference'
    elementFormDefault='qualified'>

  <xs:element name='x'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='empty'>
          <xs:attribute
              name='jid'
              type='xs:string'
              use='required'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name='empty'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value=''/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
  ]]></code>
</section1>

</xep>

=== g2p/xsf-documentation/extensions/xep-0213.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>XMPP Intermediate Client 2008</title>
  <abstract>This document defines the XMPP Intermediate Client 2008 compliance level.</abstract>
  &LEGALNOTICE;
  <number>0213</number>
  <status>Experimental</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XMPP IM</spec>
    <spec>XEP-0045</spec>
    <spec>XEP-0071</spec>
    <spec>XEP-0085</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>N/A</shortname>
  &stpeter;
  <revision>
    <version>0.1</version>
    <date>2007-04-20</date>
    <initials>psa</initials>
    <remark><p>Initial published version.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2007-03-30</date>
    <initials>psa</initials>
    <remark>First draft, split from XEP-0117.</remark>
  </revision>
</header>
<section1 topic='Introduction' anchor='intro'>
  <p>The &XSF; defines protocol suites for the purpose of compliance testing and software certification. This document specifies the XMPP Intermediate Client 2008 certification level.</p>
</section1>
<section1 topic='Definition' anchor='def'>
  <p>The XMPP Intermediate Client 2008 certification level is defined as follows:</p>
  <table caption='Required and Recommended Specifications'>
    <tr>
      <th>Specification</th>
      <th>Requirement Level</th>
    </tr>
    <tr>
      <td><strong>XMPP Basic Client 2008</strong></td>
      <td>REQUIRED</td>
    </tr>
    <tr>
      <td>&xep0045;</td>
      <td>REQUIRED</td>
    </tr>
    <tr>
      <td>&xep0071;</td>
      <td>REQUIRED</td>
    </tr>
    <tr>
      <td>&xep0085;</td>
      <td>REQUIRED</td>
    </tr>
  </table>
  <p>Note: These protocols have their own dependencies, which include the following XEPs (as well as various IETF RFCs and W3C specifications):</p>
  <ul>
    <li>&xep0004;</li>
    <li>&xep0068;</li>
    <li>&xep0082;</li>
  </ul>
</section1>
<section1 topic='Security Considerations' anchor='security'>
  <p>This document introduces no additional security considerations above and beyond those defined in the documents on which it depends.</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p> 
</section1>
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <p>This document requires no interaction with the &REGISTRAR;.</p> 
</section1>
</xep>
